# Generated by Django 4.2 on 2024-09-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
